### ISSUE TITLE
Exercise 0 Part 3

### ISSUE THREAD

**Issue by mugi-hub** [NorhanKhaled/SkillsAcademy-CAD#11]
I had acquired a cloud account before,  my account type is trial (free) as shown in the screenshot.The screenshot provided in Exercise 0 part 3 indicates a Lite(free) account. Are my account settings okay? Please advise
![Account settings](https://user-images.githubusercontent.com/58670332/80975628-03665f00-8e2b-11ea-986a-d9a267ecebb1.PNG)

**Comment by karim-elbawab** [comment]
@mugi-hub I think you have already applied a voucher code before, so I think that's fine.
