### ISSUE TITLE
Part 12.Installing the IBM Cloud developer tools CLI plug-in

### ISSUE THREAD

**Issue by rdomga** [NorhanKhaled/SkillsAcademy-CAD#12]
At this step, when i run the command "ibmcloud plugin install dev" i get the following output :
"Recherche de 'dev' dans le référentiel 'IBM Cloud'...
Plug-in 'dev 2.4.7' trouvé dans le référentiel 'IBM Cloud'
Tentative de téléchargement du fichier binaire...
 27.62 MiB / 27.62 MiB [===========================================] 100.00% 26s
28960766 octets téléchargés
Installation du fichier binaire...
ECHEC
Le plug-in 'dev' est déjà en cours d'utilisation dans l'interface de ligne de commande IBM Cloud."
The plug-in 'dev' is already in using in this IBM cloud command interface.
How to deal with this issue? 
Thank you in advance for your response

**Comment by NorhanKhaled** [comment]
it is fine 
you can skip this error message and continue the exercise
