### ISSUE TITLE
part9 and 10 in exercise0

### ISSUE THREAD

**Issue by LobnaEssmat** [NorhanKhaled/SkillsAcademy-CAD#15]
i cann't install the remaining installations start from part 9 so i'm asking for any alternative solution as online link to apply exercises online , till my issue sixed

**Comment by NorhanKhaled** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/21022185/81071917-0f672500-8eee-11ea-828e-d2d7372df28a.png)
you can use IBM Cloud Shell from here to perform the exercises :) I highlighted for you

**Comment by LobnaEssmat** [comment]
[](url)
