### ISSUE TITLE
Signing in issue

### ISSUE THREAD

**Issue by YousssifElmogy** [NorhanKhaled/SkillsAcademy-CAD#17]
i cannot find dashboard and the content of the sessions
![ibm](https://user-images.githubusercontent.com/62853374/81067008-50efd400-8ede-11ea-9ef6-6fa12cd8567f.JPG)

**Comment by kareem-zakaria** [comment]
Try using a different browser.

**Comment by YousssifElmogy** [comment]
> Try using a different browser.

yeah it worked, thanks

**Comment by kareem-zakaria** [comment]
Anytime!
