### ISSUE TITLE
Problem in installing dev plugin

### ISSUE THREAD

**Issue by narendrabluecrest** [NorhanKhaled/SkillsAcademy-CAD#19]
Please see the error coming after running the command to install the plugin dev. Please help me out to setup the environment for cloud course.

C:\Users\Dean>ibmcloud plugin install dev
Looking up 'dev' from repository 'IBM Cloud'...
Plug-in 'dev 2.4.7' found in repository 'IBM Cloud'
Attempting to download the binary file...
 27.63 MiB / 27.63 MiB [================================================================================] 100.00% 2m42s
28967936 bytes downloaded
Installing binary...
FAILED
Plug-in 'dev' is already in use in IBM Cloud CLI.

**Comment by NorhanKhaled** [comment]
ignore this error message and continue
