### ISSUE TITLE
Not Able to Download dev from ibm cloud 

### ISSUE THREAD

**Issue by Salma-tharwat** [NorhanKhaled/SkillsAcademy-CAD#2]
Please find attached my error screenshot
![Capture](https://user-images.githubusercontent.com/37934315/80963251-d99f3f00-8e0e-11ea-8255-493f29dbb66f.PNG)

**Comment by ricotomax** [comment]
> 
> 
> Please find attached my error screenshot
> ![Capture](https://user-images.githubusercontent.com/37934315/80963251-d99f3f00-8e0e-11ea-8255-493f29dbb66f.PNG)

I am facing the same issue. see screenshot (sorry I had opened a ticket for the same hadn't realized you had opened the same_
![error installing plugin show dev](https://user-images.githubusercontent.com/10231475/80964434-87afe680-8e19-11ea-962d-5e4e369a5bd5.JPG)

**Comment by Salma-tharwat** [comment]
Yes this is the same issue i have

**Comment by NorhanKhaled** [comment]
Hey 
please Run the following command 
ibmcloud dev help

if the output is 
NAME:
   ibmcloud dev - Create, develop, deploy, and monitor applications

USAGE:
   ibmcloud dev command [arguments...] [command options]

VERSION:
   2.4.7

then skip the error message

**Comment by Salma-tharwat** [comment]
this is the output, i skip it ?

**Comment by NorhanKhaled** [comment]
yes

**Comment by ricotomax** [comment]
works for me!
![image](https://user-images.githubusercontent.com/10231475/81017332-e6518080-8e6a-11ea-877d-a430a8c57bef.png)
