### ISSUE TITLE
Error Installing Plugin dev

### ISSUE THREAD

**Issue by briankasozi** [NorhanKhaled/SkillsAcademy-CAD#25]
I
![dev error](https://user-images.githubusercontent.com/6900573/81108212-03488b00-8f21-11ea-830a-40575016ed4f.PNG)

I have tried to install dev, however, it keeps returning an error, It shows that dev is already installed but then when I check the details, it shows that it's not installed.
Details are in the attached image.

**Comment by NorhanKhaled** [comment]
ignore this error message , dev tools become part from ibmcloud cli 
you can test that by running ibmcloud dev help 
this command should work
