### ISSUE TITLE
IBM Cloud email and taskes handing

### ISSUE THREAD

**Issue by kareemelkasaby1** [NorhanKhaled/SkillsAcademy-CAD#26]
Are we mandated to create the IBM Cloud account with the same email of IBM Skills Academy or not?

And how will we hand the assignments like day two's assignment of deploying node app?

**Comment by NorhanKhaled** [comment]
No you don't have to create the IBM Cloud account with the same email of IBM Skills Academy 
and you can make the exercises and if you have issues , feel free to post it on the repo
