### ISSUE TITLE
Exercises1 , IBMCloud login problem

### ISSUE THREAD

**Issue by sabreensalama** [NorhanKhaled/SkillsAcademy-CAD#28]
i can't login to ibm using cli using username and password  , failed password is  incorrect although i am sure of it , but i can do it using passcode and it expire in less time , second problem i can't make my space dev , the problem failed
![Screenshot from 2020-05-05 23-05-35](https://user-images.githubusercontent.com/22060592/81117216-02b2f300-8f27-11ea-9270-fcfe6139f905.png)
![Screenshot from 2020-05-05 23-06-26](https://user-images.githubusercontent.com/22060592/81117226-06df1080-8f27-11ea-8a00-acc6fc32bbc6.png)

**Comment by kareem-zakaria** [comment]
I'm not sure about the login issue, but I noticed that you are using this command "**ibmcloud target -g RESOURCE_GROUP**" without choosing a valid resource group.

You should replace **RESOURCE_GROUP** with the name of the desired resource group.
Ex: **ibmcloud target -g default**

I ran this command to list the available resource groups: **ibmcloud resource groups**
This was the output:
![image](https://user-images.githubusercontent.com/50543444/81131416-5f280980-8f4b-11ea-833b-36ca8c1945ea.png)

As you can see the name of the available resource group is **default**.

I hope this helps.

**Comment by tafoca** [comment]
I use here ibmcloud resource groups to see all groups and change case of name default to **Default** ibmcloud target -g Default
