### ISSUE TITLE
Can't use IBM cloud account, university email is useless, Can't use same email registered to IBM skills academy

### ISSUE THREAD

**Issue by atefhares** [NorhanKhaled/SkillsAcademy-CAD#29]
I have a university email and I used it to register to IBM skills academy but I am still not able to complete this step:
it says your university not registered

![Selection_048](https://user-images.githubusercontent.com/14354272/81117178-f6c73100-8f26-11ea-8004-474bb8b57eb6.png)

-------

Also I have an account on IBM cloud [with the same university email] and I used a promo code from `cognitiveclass.ai` last year and subscription is finished, now whenever I log into my account it blocks me showing this pop up and asks me to add a credit card! 
I can't even use the free tier, the only options available is to add a new promo code or use credit card

![Selection_049](https://user-images.githubusercontent.com/14354272/81117638-b7e5ab00-8f27-11ea-82cc-163b431a6996.png)

**Can I use another account on ibm cloud instead of the one registered at IBM skills academy?** 

------
related issues

#10 #26

**Comment by NorhanKhaled** [comment]
you can register with another email on IBM Cloud
