### ISSUE TITLE
Error Installing the IBM Cloud developer tools CLI plug-in

### ISSUE THREAD

**Issue by ricotomax** [NorhanKhaled/SkillsAcademy-CAD#3]
Hi Norhan, 
In the Exercise 0 - setting up hands on environment, page 18 section #12 Installing the IBM Cloud developer tools CLI plug-in
I face the below issues

When I run the command >ibmloud plugin show dev
I get the error
FAILED
plug-in 'dev' was not installed

Additionally when I run the command >ibmcloud plugin install dev
I get the error 
Installing binary 
FAILED. 

_Screenshot attached
![error installing plugin show dev](https://user-images.githubusercontent.com/10231475/80964167-0fe1bc00-8e19-11ea-8825-84bb8d0f9497.JPG)
_

**Comment by NorhanKhaled** [comment]
Hey
please Run the following command
ibmcloud dev help

if the output is
NAME:
ibmcloud dev - Create, develop, deploy, and monitor applications

USAGE:
ibmcloud dev command [arguments...] [command options]

VERSION:
2.4.7

then skip the error message

**Comment by ricotomax** [comment]
it works! Thanks Norhan
![image](https://user-images.githubusercontent.com/10231475/81017396-0da84d80-8e6b-11ea-8330-4ef5c740b65f.png)
