### ISSUE TITLE
Failed Error in Part 12 Ex 0 

### ISSUE THREAD

**Issue by m-jaysule** [NorhanKhaled/SkillsAcademy-CAD#30]
I run the command from part 12 of Ex 0 and I get a "FAILED" when installing binary 

Attached is a screen shot 

<img width="569" alt="Screen Shot 2020-05-06 at 00 37 36" src="https://user-images.githubusercontent.com/52970407/81123019-6abb0680-8f32-11ea-8edb-b434e3af31d8.png">

**Comment by NorhanKhaled** [comment]
ignore this error message
