### ISSUE TITLE
Queries

### ISSUE THREAD

**Issue by gemin55** [NorhanKhaled/SkillsAcademy-CAD#33]
Hi 

1.
Let's say I have 20 students who are deploying their app on IBM cloud. What is the storage capacity for the lite account?

2. 
Does the deployed app on lite account have an expiry date? 
How long does the random key (UUID) lasts?
 
Thank you

**Comment by NorhanKhaled** [comment]
This question has been answered in the session 
please confirm you got the answer

**Comment by gemin55** [comment]
Yes got it thank you
