### ISSUE TITLE
IBM Cloud developer tools

### ISSUE THREAD

**Issue by Adolph-HTU** [NorhanKhaled/SkillsAcademy-CAD#34]
I am unable to install the IBM Cloud developer tools after downloading several times. After running 
**ibmcloud plugin install dev**
 I get the error message below.
**Installing Binary 
"Failed"**

![image](https://user-images.githubusercontent.com/64895692/81160319-71b93780-8f79-11ea-9f62-d558318e4a78.png)

**Comment by morexwell** [comment]
ignore

**Comment by Adolph-HTU** [comment]
Is that not why the cloud foundry commands are not running for me?

**Comment by NorhanKhaled** [comment]
no it is not the case , you will need to ignore this error message and continue with the exercise
