### ISSUE TITLE
Failure: Installing the IBM Cloud developer tools CLI plug-in

### ISSUE THREAD

**Issue by senjack** [NorhanKhaled/SkillsAcademy-CAD#36]
I am in the last step of Exercise 0. but i keep on getting this challenge every time i attempt to install the IBM plugins.

$ ibmcloud plugin install dev
Looking up 'dev' from repository 'IBM Cloud'...
Plug-in 'dev 2.4.7' found in repository 'IBM Cloud'
Attempting to download the binary file...
 27.63 MiB / 27.63 MiB  100.00% 1m10ss
28967936 bytes downloaded
Installing binary...
FAILED
Plug-in 'dev' is already in use in IBM Cloud CLI. 

What should I do.

**Comment by NorhanKhaled** [comment]
ignore this error message and continue
