### ISSUE TITLE
pushing into the cloud

### ISSUE THREAD

**Issue by bfalah** [NorhanKhaled/SkillsAcademy-CAD#37]
If we have two different apps in the same folder and we use push command, how a particular app is known to be pushed since we are using only the following command : ibmcloud cf push

**Comment by NorhanKhaled** [comment]
you can't have two applications in the same folder , ibmcloud cf push checks the manifest file which contains the application details and pushes the application , you can't have two manifest files in the same directory

**Comment by kareem-zakaria** [comment]
As @NorhanKhaled said you cannot have two manifest files in the same directory, but if you have two applications in separate directories and you wish to deploy only one of them you can use the same command specifying the application name.

Here is the command: '**ibmcloud cf push <app_name>**'

By replacing **<app_name>** with the name of your chosen application, you will deploy only the chosen application.

Please @NorhanKhaled correct me if I'm wrong.

This was my reference: https://cloud.ibm.com/docs/cloud-foundry?topic=cloud-foundry-deploy_apps

I hope this helps.
