### ISSUE TITLE
Issues with Part 12 in Exercise 0 - Dev Installation - Kanaksabee

### ISSUE THREAD

**Issue by gemin55** [NorhanKhaled/SkillsAcademy-CAD#4]
Cannot install the DEV!!

![Capture](https://user-images.githubusercontent.com/64786948/80968243-a9649a00-8e28-11ea-9788-c6a26e6332e7.JPG)

**Comment by jbyabazaire** [comment]
I also have the same problem. working on windows 10

**Comment by NorhanKhaled** [comment]
Hey
please Run the following command
ibmcloud dev help

if the output is
NAME:
ibmcloud dev - Create, develop, deploy, and monitor applications

USAGE:
ibmcloud dev command [arguments...] [command options]

VERSION:
2.4.7

then skip the error message

**Comment by bfalah** [comment]
I have also the same problem. 
When I run the command **ibmcloud dev help**, I got the same thing except for the version which is 2.4.8 instead of 2.4.7

**Comment by kareem-zakaria** [comment]
![image](https://user-images.githubusercontent.com/50543444/81010822-2c044e00-8e57-11ea-8a82-c0acf16bbcda.png)

@bfalah I think you have installed it, you don't have a problem.

**Comment by gemin55** [comment]
Thank you
