### ISSUE TITLE
ibmcloud plugin install dev error

### ISSUE THREAD

**Issue by pascalnyapoto** [NorhanKhaled/SkillsAcademy-CAD#41]
I am not able to install the dev plugin, with the following error: 
Installing binary...
FAILED
Plug-in 'dev' is already in use in IBM Cloud CLI.

![ibmcloud plugin install error](https://user-images.githubusercontent.com/64908108/81182923-21f96100-8fb7-11ea-8809-3700318ec764.png)

**Comment by karim-elbawab** [comment]
@pascalnyapoto yes so you have no problem, as the latest version of the IBM CLI tool already includes this plugin.
