### ISSUE TITLE
CLOUD-EX01 ibmcloud cf push 

### ISSUE THREAD

**Issue by morexwell** [NorhanKhaled/SkillsAcademy-CAD#44]
Opening the sample app folder and running " ibmcloud cf push "
The error I get is 
 "
no org targeted, use 'cf.exe target -o org' to target an org. FAILED ''

I have also run " ibmcloud target -o ORG"

I got no record of organization... 

I really appreciate any assistance.

Thank you.

**Comment by kareem-zakaria** [comment]
You should replace **ORG** in the command '**ibmcloud target -o ORG**' with the name of the organization. **ORG** is just a place where you should insert your organization name.

For example: -
When you run this command '**ibmcloud account orgs**', it will list the available organizations.

You should see something like this:
![image](https://user-images.githubusercontent.com/50543444/81238241-d4eeac80-9001-11ea-83cf-a399e01daaa9.png)

Then simply run the first command again which is '**ibmcloud target -o ORG**', but replace **ORG** with the name of the organization.

As per my example the command would look like this:
'**ibmcloud target -o kareemahmed96@outlook.com**'

**Comment by morexwell** [comment]
I dont know what is missing here!

When I ran the command **"ibmcloud account orgs"** i got 

> organization not found.

please see screenshot

![no org found](https://user-images.githubusercontent.com/11416140/81257765-f7280080-8fe8-11ea-8237-b55e1fcd2dc2.JPG)

when I login to my cloud foundry dash board.. i can see the org name that I created there.
![cloud foundry Orgs name](https://user-images.githubusercontent.com/11416140/81257892-440bd700-8fe9-11ea-81e2-40810e599f8a.JPG)
  
when I try to create one ...  it says it already exist. 

![trying to create](https://user-images.githubusercontent.com/11416140/81258026-977e2500-8fe9-11ea-8e18-a027ba10ee62.JPG)

when i check again via CLI command it says not found...

Is there anything  missing?

originally, what i am trying to do is to use this command
**ibmcloud cf push**  to deploy my app to cloud foundry.

Any assistance will be appreciated.

Thank you

**Comment by morexwell** [comment]
Yah!!! i figured it out. Thanks

**Comment by kareem-zakaria** [comment]
You're welcome!

Best of luck.
