### ISSUE TITLE
Exercise 3: Part 6

### ISSUE THREAD

**Issue by gemin55** [NorhanKhaled/SkillsAcademy-CAD#48]
**Hello
Part 6 of exercise 3 not working: see screenshot below:
It's not returning access_token
Then i generated the token from the CLI 
But still i am getting the following error:**

![image](https://user-images.githubusercontent.com/64786948/81260717-a1387480-904b-11ea-9871-8dde42212bc4.png)

**Then why i try to use the access token in the get request to show all docs from the novels database, then i get the following error message:**

![image](https://user-images.githubusercontent.com/64786948/81260989-3cc9e500-904c-11ea-8257-b33147fc061c.png)

Please help

**Comment by Karen-ceo** [comment]
There is some special chars beside the key name please delete them and try again

**Comment by gemin55** [comment]
Thx..
