### ISSUE TITLE
Exercise 01 Failed Error

### ISSUE THREAD

**Issue by Adolph-HTU** [NorhanKhaled/SkillsAcademy-CAD#49]
I get this error whenever i run the following command

Ibmcloud cf push vy301- c37-nodesample

![image](https://user-images.githubusercontent.com/64895692/81285779-8d8f0d00-904f-11ea-9f6b-5f0f8f7f8ddb.png)

**Comment by NorhanKhaled** [comment]
ignore this error message and continue
