### ISSUE TITLE
issue in ex0 part12:

### ISSUE THREAD

**Issue by kipyego3** [NorhanKhaled/SkillsAcademy-CAD#6]
![image](https://user-images.githubusercontent.com/64788335/80971686-cc417f00-8e25-11ea-9ca8-128176d2fbc5.png)

**Comment by NorhanKhaled** [comment]
Hey
please Run the following command
ibmcloud dev help

if the output is
NAME:
ibmcloud dev - Create, develop, deploy, and monitor applications

USAGE:
ibmcloud dev command [arguments...] [command options]

VERSION:
2.4.7

then skip the error message

**Comment by kipyego3** [comment]
yes, I run the command and i got the same feedback you just posted. thanks again.
