### ISSUE TITLE
Exercise 3. Unauthorized Error Issue

### ISSUE THREAD

**Issue by bfalah** [NorhanKhaled/SkillsAcademy-CAD#61]
Hi,
When I tired to view all document in Postman I got the following error:
{
    "error": "unauthorized",
    "reason": "_reader access is required for this request"
}

even if I followed all the required steps one by one including the token.
Any help is appreciated

**Comment by KTRDeveloper** [comment]
Check that you preceded the token with 'Bearer  '.  The value of the **Authorization** key in the header should be "**Bearer** TOKEN" not "TOKEN".
For instance 
key : Authorization
value : **Bearer** eyJraWQiOiIyMDIwMDQyNTE4MjkiL...
