### ISSUE TITLE
Failure to install ibm plugins on my windows 10 OS Machine

### ISSUE THREAD

**Issue by Godwill92** [NorhanKhaled/SkillsAcademy-CAD#63]
I am trying to install the ibm plugins on my computer and there are error messages, i have tried to find a solution online but still i am having the same problem. i have attached a Screenshot of the error message. I need help, i can't do the exercises

![Screenshot](https://user-images.githubusercontent.com/44298533/81509775-5a79a180-930d-11ea-8bbd-45f63108033e.PNG)

**Comment by KTRDeveloper** [comment]
You should first download and install IBM cloud CLI at [https://clis.cloud.ibm.com/download/bluemix-cli/latest/win64](https://clis.cloud.ibm.com/download/bluemix-cli/latest/win64) (Just follow the steps of Exercise 0 part 4)

**Comment by KTRDeveloper** [comment]
> I am trying to install the ibm plugins on my computer and there are error messages, i have tried to find a solution online but still i am having the same problem. i have attached a Screenshot of the error message. I need help, i can't do the exercises
> 
> ![Screenshot](https://user-images.githubusercontent.com/44298533/81509775-5a79a180-930d-11ea-8bbd-45f63108033e.PNG)

k

**Comment by Godwill92** [comment]
I have downloaded and install everything. The only problem i am facing is when installing CLI plugin using command line

**Comment by KTRDeveloper** [comment]
> I have downloaded and install everything. The only problem i am facing is when installing CLI plugin using command line

It appears on the screenshot that the system does not recognize the **ibmcloud** command. so make sure that IBM Cloud CLI has been installed correctly. You can try reinstall it and use "ibmcloud --version" to check that it succeeded.

You can also edit your system PATH variable to include the path to the executable, that is "C:\Program Files\IBM\Cloud\bin"

**Comment by Godwill92** [comment]
Thank you, i reinstalled and chose the repair option and then it's now working. i am installing now. Thank you!
