### ISSUE TITLE
Cloud-Ex03 - Issue accessing the Cloudant Dashboard - Unit 6. - Module II.

### ISSUE THREAD

**Issue by kareem-zakaria** [NorhanKhaled/SkillsAcademy-CAD#67]
I have an issue trying to access the **Manage** tab for the Cloudant Service.

![Cloudant-Annotation 2020-05-11 142531](https://user-images.githubusercontent.com/50543444/81567351-7d9f6200-939c-11ea-965f-147cce9523d7.png)

I tried using a private window, clearing the cache, and switched to a different browser "Firefox". Unfortunately the issue still persists.

![Cloudant-Firefox-Annotation 2020-05-11 143335](https://user-images.githubusercontent.com/50543444/81567490-ab84a680-939c-11ea-9878-51ff554edaf6.png)

I checked the details for the Cloudant Service, and it shows that it's status is active.

![Annotation 2020-05-11 153027](https://user-images.githubusercontent.com/50543444/81567594-cfe08300-939c-11ea-8915-f465765733db.png)

Thank you in advance.

**Comment by Karen-ceo** [comment]
please delete this service and re-create it , it wasn't created properly

**Comment by kareem-zakaria** [comment]
@Karen-ceo I have tried re-creating it several times, maybe it is something related to the DNS server?

I found this article: https://geeksadvice.com/how-to-fix-dns_probe_finished_nxdomain-error/

I will try these methods and update you with what happens.

**Comment by kareem-zakaria** [comment]
The problem has been resolved.

These are the steps that worked for me, so that anyone with same problem can benefit from:

1. Flush the DNS and configure the DNS server addresses.

2. Reset the **hosts** file located in **%WinDir%\System32\Drivers\Etc**
    I have attached the default **hosts** file here: [hosts.txt](https://github.com/NorhanKhaled/SkillsAcademy-CAD/files/4611749/hosts.txt)

Here is the link to my reference: https://support.microsoft.com/en-au/help/972034/how-to-reset-the-hosts-file-back-to-the-default

**Comment by Karen-ceo** [comment]
good Job and thanks for sharing

**Comment by kareem-zakaria** [comment]
> good Job and thanks for sharing

You're welcome!
