### ISSUE TITLE
Exercise 6: Steps are not same like in handout

### ISSUE THREAD

**Issue by gemin55** [NorhanKhaled/SkillsAcademy-CAD#70]
Hi . 
The steps provided in exercise 6 are not the same when we run the commands in the command prompt to generate a starter kit.
Instead of select blank app, i am getting this :
![image](https://user-images.githubusercontent.com/64786948/81647048-6ebcbc00-943d-11ea-9052-857505f05230.png)

Then it's asking other options which is not in the exercise, for example:
![image](https://user-images.githubusercontent.com/64786948/81647110-898f3080-943d-11ea-8e61-caff59b44568.png)

I am also not able to run the following command:
![image](https://user-images.githubusercontent.com/64786948/81647183-a6c3ff00-943d-11ea-843d-ce7d1b5d65d0.png)

Please help.
Thank you

**Comment by KTRDeveloper** [comment]
I also noticed that. But to continue the exercise, I chose the following sequence:

` 1.  back end Service / Web  App ---> 4. Node --->  3. Node.js Express App - Start building your next Node.js Express app on IBM Cloud.`
`

**Comment by gemin55** [comment]
Hi Norhan

Greetings

Yes I did same finally and manage to get it to work.
Thanx again.
