### ISSUE TITLE
After a Feature code activation, i have a problem with my IBM cloud account.

### ISSUE THREAD

**Issue by rdomga** [NorhanKhaled/SkillsAcademy-CAD#72]
After i activate the feature code on my IBM cloud account, the free plan is no longer available on my account.
The attached document gives some
[PB_WITH_MY_ACCOUNT_AFTER_FEATURE_CODE_ACTIVATION.pdf](https://github.com/NorhanKhaled/SkillsAcademy-CAD/files/4615182/PB_WITH_MY_ACCOUNT_AFTER_FEATURE_CODE_ACTIVATION.pdf)
 pictures

**Comment by AminTun** [comment]
I have the same problem... I although created the App (it failed the first time, then could start it manually...)

**Comment by rdomga** [comment]
Thanks you for tour response. I think it is ok now. Yesterday, i did
Exercice 1 and 2 without any Problem.

Regards

Domga
