### ISSUE TITLE
Exercise 6 

### ISSUE THREAD

**Issue by mariosenam** [NorhanKhaled/SkillsAcademy-CAD#75]
Which option do i choose

![as](https://user-images.githubusercontent.com/7712540/81806878-ff1a0000-9514-11ea-840a-af7898f94dc3.png)

**Comment by faouziabenabbou** [comment]
I have this issue
![image](https://user-images.githubusercontent.com/64813598/81817529-625b6080-951c-11ea-8adf-cdd31741c8aa.png)
please how to fix it,

**Comment by faouziabenabbou** [comment]
how to fix organization problem (not found)?

**Comment by morexwell** [comment]
Choose 3 by typing 3
