### ISSUE TITLE
exercice 6 ,connexion

### ISSUE THREAD

**Issue by faouziabenabbou** [NorhanKhaled/SkillsAcademy-CAD#76]
hi,
the command kubectl version -short worked yesteday and now no:
![image](https://user-images.githubusercontent.com/64813598/81807157-1bb23a00-950d-11ea-8879-001d3e7cf4f5.png)
![image](https://user-images.githubusercontent.com/64813598/81807479-a8f58e80-950d-11ea-9a95-a51a66da7905.png)

**Comment by faouziabenabbou** [comment]
can someone help me ?

**Comment by KTRDeveloper** [comment]
Use double dash (`--short`) not single dash that is `kubectl version --short`

**Comment by NorhanKhaled** [comment]
kubectl version --short , and as I can see you need to run the command  ibmcloud ks cluster config --cluster mycluster 
then take the environment variable and paste it to be connected to the cluster

**Comment by faouziabenabbou** [comment]
thank you
