### ISSUE TITLE
Query?

### ISSUE THREAD

**Issue by gemin55** [NorhanKhaled/SkillsAcademy-CAD#84]
Hi
May i know the importance of the square bracket? 
Is it mandatory? Will it make a difference if we remove the square brackets?

![image](https://user-images.githubusercontent.com/64786948/81931844-c6088b00-95fb-11ea-84ec-e7a6833d70a3.png)

**Comment by NorhanKhaled** [comment]
Translations here takes an Array so we added a [] so it is mandatory 
it should not work if you remove it as it expects an array not a JSON object

**Comment by gemin55** [comment]
Thx
