### ISSUE TITLE
Exercise 5, Part 2: Downloading configuration files to access Kubernetes

### ISSUE THREAD

**Issue by HudsonLubinga** [NorhanKhaled/SkillsAcademy-CAD#87]
When is use this command: ibmcloud ks cluster-config mycluster, I get and error, even if I remove the  hythen(-), it fails. and the previous command: ibmcloud ks cluster config --cluster mycluster does not output the KUBECONFIG variable. Please help me. Thanks
![image1](https://user-images.githubusercontent.com/64992223/82037686-286c9480-96ab-11ea-823d-5f3c7b1ca7bd.PNG)

**Comment by KTRDeveloper** [comment]
The right command is `ibmcloud ks cluster config --cluster <cluster_name_or_ID>` . As shown by your screenshot, this command executed successfully.  You can check that the files was really downloaded by navigating to `C:\Users\user_name>\.bluemix\plugins\container-service\clusters\mycluster\kube-config-mel01-mycluster.yml` . So all what you need is to set the environment variable with `SET KUBECONFIG=C:\Users\<user_name>\.bluemix\plugins\container-service\clusters\mycluster\kube-config-mel01-mycluster.yml` and continue the exercise.

**Comment by HudsonLubinga** [comment]
Thanks so much
