### ISSUE TITLE
materials

### ISSUE THREAD

**Issue by habiba88** [NorhanKhaled/SkillsAcademy-CAD#9]
where could i find the presentation,exercise 0 and all materials of the course
i have logged in and opened dashboard but i couldn't find anything
![issue](https://user-images.githubusercontent.com/64789742/80974402-88268e00-8dd5-11ea-9163-e26ee3fb560d.PNG)

**Comment by NorhanKhaled** [comment]
https://www-03.ibm.com/services/weblectures/dlv/protected/GateProt.wss?handler=LoginSSL&sequence=3&customer=meap&offering=meal&action=display_career_path_roadmap&curriculum=meal_217&language=&from=top_navigation

I sent you the direct link

**Comment by habiba88** [comment]
when i open this link this screen appears to me
but when i open " my IBM" the cloud course appears  with a launch tab but still i can't find materials or even the 2 modules that i should read

![issue2](https://user-images.githubusercontent.com/64789742/81009546-b8881f80-8e09-11ea-97cb-dfc0635ab52f.PNG)

**Comment by kareem-zakaria** [comment]
Make sure you have applied your voucher to your  account, then navigate to your Dashboard.

This is the link where you can enter your voucher: https://www-03.ibm.com/services/weblectures/dlv/Gate.wss?handler=Login&action=index&customer=meap&offering=meai&from=short_url5&origin=global

Then you will find the materials inside the **Cloud Application Developer** Career Path.

![image](https://user-images.githubusercontent.com/50543444/81011564-7803c280-8e58-11ea-925b-fdb152e2ae7f.png)


![image](https://user-images.githubusercontent.com/50543444/81011283-f6139980-8e57-11ea-8367-dac9e41b08c8.png)

**Comment by habiba88** [comment]
this voucher worked yesterday and the course in first picture appeared but no materials
but when i sign in with the same voucher now it seems that it doesn't work!
![launch](https://user-images.githubusercontent.com/64789742/81017023-64376c80-8e16-11ea-87a8-abe7f3d22293.PNG)

![voucher doesn't exist](https://user-images.githubusercontent.com/64789742/81016841-0e62c480-8e16-11ea-9cd6-58815cab2125.PNG)

**Comment by kareem-zakaria** [comment]
This means that you have used that voucher with a different account. Try to log in using that account in order to benefit from the voucher.

The voucher can only be used with one email account.

Use the same link but instead of entering the voucher press on **Log in**, and use your IBMid account to login.

Link: https://www-03.ibm.com/services/weblectures/dlv/Gate.wss?handler=Login&action=index&customer=meap&offering=meai&from=short_url5&origin=global


![image](https://user-images.githubusercontent.com/50543444/81017298-6f17ee80-8e62-11ea-89b7-7f03139c00fa.png)

**Comment by habiba88** [comment]
I tried from the login tab but it doesn't work too, i logged in yesterday with same IbmID and cloud course appeared like this in the screenshot  so it worked! what is the problem
![launch](https://user-images.githubusercontent.com/64789742/81019257-25f07c00-8e1b-11ea-85bc-de885cacccf9.PNG)

**Comment by kareem-zakaria** [comment]
@NorhanKhaled Is it allowed to share the course content here so that she can benefit from the material until this issue is resolved?

I can upload them to this thread if it is approved.

**Comment by habiba88** [comment]
i tried from the login tab but it doesn't work too and i have no other account,could you help me accessing the course in any other way!!
or if you could check when its used or email its used with

**Comment by hazem24** [comment]
Okay this problem happened to me also.

1. Please Open your account from **FireFox** Browser, 
2. Then go to the link mentioned by Norhan Khaled.
3. Sign in into your account then you will be redirect to a form complete it, after that Dashboard tap will appear to you, don't worry you will find all matrials inside your account.

I hope this help you.

**Comment by habiba88** [comment]
unfortunately it doesn't work
![firefox](https://user-images.githubusercontent.com/64789742/81059314-16a61880-8e85-11ea-8a5f-22e9b9c33628.PNG)

**Comment by habiba88** [comment]
problem solved ,thank you
